export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";
export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";

export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";
export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
